name: Build and push docker image to Docker Hub

on:
  workflow_run:
    workflows: ['Build, test and push coverage']
    types:
      - completed
    branches: ['main']

jobs:
  run:
    uses: ./.github/workflows/build-and-push-container_reusable.yml
    with:
      version: latest