name: Build, test and push coverage

on:
  push:
    branches: [main]

jobs:
  run:
    uses: ./.github/workflows/build_test_and_coverage_reusable.yml
    with:
      coverage: true
    secrets:
      codecov: ${{ secrets.CODECOV_TOKEN }}