# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and test

on:
  pull_request:
    branches: ['*']

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...